### PR TITLE
switch to pycryptodome - a maintained fork of pycrypto

### PR DESCRIPTION
**Pull request by mindw**
https://pypi.python.org/pypi/pycryptodome - maintained, many additions and binary wheels!
add py36 to tox.

Tested on windows py35 & py36.

### CODE REVIEW

**Comment by kurtbrose** [comment]
thanks!  I'll need to do a bit of research on `pycryptodome` before merging but on the face of it this looks like a good change

Also, I may shift this around to use extra dependencies: http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

So, you can pip install pyjks[cryptodome] or pyjks[cryptography] to use whichever backend is preferred.

**Comment by mindw** [comment]
I would suggest to keep this simple and continue require as before - pip does not list extras (at least older versions).
The PR is for pycryptodome as it is a drop in replacement. switching to cryptography seems a lot more disruptive.
One issue to consider to use pycryoptodomex to avoid package collision with pycrypto.

**Comment by kurtbrose** [comment]
agree, I think switching to extra dependencies is an orthogonal issue

**Comment by kurtbrose** [comment]
this is clearly an improvement, I'm going to merge and we will fix it forward if anything else needs to be ironed out :-)

**Comment by mahmoud** [comment]
Having reviewed [pycryptodome's changelog](https://github.com/Legrandin/pycryptodome/blob/master/Changelog.rst), I think this is likely a fine improvement. There are some backwards incompatibilities, but I don't think we'll hit any of them.

**Comment by mahmoud** [comment]
PyJKS version 17.1.0 is now tested and released on PyPI. `pip install pyks==17.1.0` at your convenience. Thanks again!

**Pull request merged**
