### PR TITLE
Allow opening a store without passphrase

### PR DESCRIPTION
**Pull request by elias5000**
In case of empty passphrase the integrity check needs to be skipped in order to be able to load a keystore.
This copies the behavior of keytool.

### CODE REVIEW

**Comment by mahmoud** [comment]
Hi Elias! This seems like a reasonable change. I had to search around for keytool behavior, because I recalled it working differently back when we used it more. Still, this [seems to mirror what some other projects have done](https://github.com/kaikramer/keystore-explorer/issues/122).

Could I motivate you to add a test? The linked PR has a keystore with a blank password already, if you'd like to borrow that one.

**Comment by elias5000** [comment]
I added a test using the truststore.jks from the PR you linked.

This is actually my use case: Opening a truststore that does not contain any private keys. I just need to get the certificates.

**Comment by mahmoud** [comment]
It's perfect, thank you! Will get this released ASAP. For now, feel free to install from master and give it a whirl. Thanks again!

**Comment by chinkinsei** [comment]
hi its quite odd to me that just silently skip the integrity check on empty passphrase, it would be **much** better to prompt "Tampered keystore or incorrect passphrase, try to open anyway?" in case passphrase/integrity check failed!

**Pull request merged**
