### PR TITLE
Adjusted asn1 encoder so that it doesn't include empty attributes

### PR DESCRIPTION
**Pull request by magnuswatn**
Fixes https://github.com/kurtbrose/pyjks/issues/34

### CODE REVIEW

**Comment by magnuswatn** [comment]
Ah, seems like the tests are pinned against pyasn1 0.1.7, which doesn't support ifNotEmpty.

**Comment by magnuswatn** [comment]
@mahmoud What do you think? Should we require pyasn1 v0.3.2 or higher, og should I make it work with older versions?

**Comment by mahmoud** [comment]
So, 0.3.2 has been out for about a year, that seems pretty reasonable. I also went through the changelog line by line since 0.1.7 and didn't see anything that looked breaking for our use, so I'm OK with a requirement upgrade. A few behaviors might change for some corner-case users, but that's what the issue tracker is for. :)

Don't forget to update the requirements.txt as well as making the setup.py `>=` entry. Thanks!

**Comment by magnuswatn** [comment]
I had to go up to 0.3.5, as there was some bugs in 0.3.2, .3 and .4. It came out just shy of a year ago, hope it's ok.

I also snuck in some other small changes.

**Comment by mahmoud** [comment]
LGTM! Thanks! :)

**Pull request merged**
