### PR TITLE
Support for creating and saving jks keystores

### PR DESCRIPTION
**Pull request by magnuswatn**
I have implemented functionality for creating and saving jks keystores. This may be of interest for you too?

### CODE REVIEW

**Comment by mahmoud** [comment]
Hey there, Magnus! On first impressions, this looks great! I think @kurtbrose will want to do a code review, and @voetsjoeba might like a look as well. But this is looking to be a very pleasant surprise! :)

**Comment by voetsjoeba** [comment]
Am taking a look, but I agree with @mahmoud, looks good on first sight. Will provide comments soon.

**Comment by kurtbrose** [comment]
I'm taking a look now, the contribution is much appreciated :-)

**Comment by mahmoud** [comment]
bumping this. @kurtbrose / @voetsjoeba if you've got a spare minute this weekend, additional review would be appreciated!

**Comment by voetsjoeba** [comment]
Apologies, I got hung up on this one.

So this patch in and of itself looks perfectly fine to me: respects and extends the existing structure and style, has documentation, has test cases, etc.

The reason I got hung up is that I think before we merge this we need to take a moment and seriously consider to what degree we are willing to take responsibility for the strength of people's keystores generated through pyjks.

This patch implements JKS keystore creation, which is fine in the sense that for JKS there are few choices to be made that impact the crypto strength.
But if we add the ability to create JKS keystores, then the obvious next question that will come in is to add support for JCEKS and BKS as well. 

Those other ones all require a choice of various cryptographic parameters that influences the strength of the crypto (salt sizes, iteration counts, etc), and I'm not so sure I want to be accountable for any particular choice of those. You could argue that we can just use whatever values the Java implementations use, but those were chosen maybe 15? 20? years ago, so then I guess we're guilty of knowingly issuing keystores with crypto that's not as good as it could be. Or we choose our own, but then that choice is still on us.

The other alternative is to disavow any responsibility for the strength of the keystores and go "use at your own risk" or something, but then why provide it in pyjks in the first place? Just let them keep using the keytool then.

**Comment by mahmoud** [comment]
@voetsjoeba That's an interesting point. Would issuing a runtime warning for insecure combinations of parameters be too involved? I think in the long run it may be. I think it's quite common for security libraries to have "use at your own risk" features. So I'm ok documenting that bridge when we come to it.

If you'd like I can reach out to some friends at the [PyCA](https://github.com/pyca/) and get their opinions.

**Comment by voetsjoeba** [comment]
Sure, can't hurt. I'm not sure how a runtime warning would work; the parameters in question would have to be a design choice of the implementation, not something that can be chosen at runtime by the user.

**Comment by mahmoud** [comment]
Oh, interesting. Didn't realize the parameters were hardcoded into the library. Some more context may be useful, if you don't mind explaining (or linking). 

As for the warnings, I was referring to [the built-in warnings module](https://docs.python.org/2/library/warnings.html). We can issue a warning, an integrator can filter it. Simple, but it works for some libs.

**Comment by voetsjoeba** [comment]
Sure. In particular, JCEKS, BKS and UBER keystores all use PBE algorithms to derive keys from the user password for the purposes of protecting the keys that are in the keystore (the exact algorithms used are listed in the "Concepts" section of the documentation).

In addition to the password input itself, PBE algorithms also require a choice of salt size and amount of iterations. Both of these affect the resilience of the key derivation scheme against e.g. brute-force or rainbow table attacks: the larger your salt size, and the more iterations you perform, the more computationally expensive it becomes for an attacker to bruteforce the password or to find it through a rainbow table.

The salt and iteration count are a choice to be made at the time the keystore is created; they are not secret, and are stored in a "plaintext" ASN.1 structure alongside the encrypted value (see e.g. RFC 2898 for a definition of the PBEParameter structure).

This implies that each implementation can make its own choice of parameters. The choices made by the JCE and BKS implementations were chosen many years ago. Are those still an adequate choice that would hold up today? I'm not qualified to answer that ...

**Comment by mahmoud** [comment]
@voetsjoeba Thanks for the background. I talked with @alex from @pyca about this, and I'd be ok with holding off on BKS/JCEKS until we get a specific feature request with respective justification. We'll just document and justify the gap in the API. 

Another thought I had, we can possibly include them as recipes in the back of the docs, too, with strong warnings around them that they should be used only if absolutely necessary. Then the decision is truly in the hands of the integrator.

**Comment by kurtbrose** [comment]
I'm going to merge.  This is a great PR everybody likes it, sorry for the slowness in reading the code and running the tests myself :-)

**Pull request merged**
